#!/bin/sh
set -ex

apt-get update
apt-get install --yes \
  ca-certificates \
  curl

# Install azure-resources-exporter
useradd -r -d /opt/azure-resources-exporter are

mkdir -p /opt/azure-resources-exporter
mv /azure-resources-exporter /opt/azure-resources-exporter

chown -R are /opt/azure-resources-exporter

# Clean
apt-get remove --purge curl --yes
apt-get autoremove --purge --yes
apt-get clean --yes

# CIS Benchmarking
sed -i 's/^PASS_MAX_DAYS.*$/PASS_MAX_DAYS   60/g' /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*$/PASS_MIN_DAYS   7/g' /etc/login.defs
sed -i 's/^UMASK.*$/UMASK   027/g' /etc/login.defs
