resource_tags:

  - tag_selections:
      Monitoring: "enabled"

  - tag_selections:
      Client: "Alice"
      Env: "Prod"
    resource_type_selections:
      - "Microsoft.Web/serverfarms"
      - "Microsoft.Web/sites"